services:
  - type: web
    name: astro
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn technician.wsgi:application
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DJANGO_SETTINGS_MODULE
        value: technician.settings